### ISSUE TITLE
Could not spend spendable outputs panic

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-node#433]
This is probably related to a channel closure that I did on this wallet. 

```
INFO mutiny-core/src/logging.rs:27
2023-04-27 20:57:04.786 INFO  [mutiny_core::esplora:220] Starting transaction sync.
[mutiny_wasm.js:2268:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:57:05.438 DEBUG [lightning::chain::chainmonitor:612] New best block 0000010118f1840b4559ce14ca2ef491e0a734e14b30a852f5de406b237e9217 at height 36878 provided via best_block_updated
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:57:05.439 DEBUG [lightning::chain::onchaintx:707] Updating claims view at height 36878 with 0 claim requests
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:57:05.439 DEBUG [lightning::chain::onchaintx:820] Updating claims view at height 36878 with 0 matched transactions in block 36878
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:57:05.439 DEBUG [lightning::chain::channelmonitor:3244] Descriptor StaticOutput 532ff37cb6c3cb28b5f3ec5f96a0373c1765ab757a7343a40737cd5f50186110:0 marked for spending has got enough confirmations to be passed upstream
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:57:05.440 DEBUG [lightning::chain::onchaintx:707] Updating claims view at height 36878 with 0 claim requests
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:57:05.440 DEBUG [lightning::chain::onchaintx:820] Updating claims view at height 36878 with 0 matched transactions in block 36878
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:57:05.442 DEBUG [event:0] EVENT: SpendableOutputs processing
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
panicked at 'could not spend spendable outputs: ()', /data/Dev/Mutiny/mutiny-node/mutiny-core/src/event.rs:527:22

Stack:

getImports/imports.wbg.__wbg_new_abda76e883ba8a5f/<@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js:2129:21
logError@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js:232:18
getImports/imports.wbg.__wbg_new_abda76e883ba8a5f@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js:2128:66
console_error_panic_hook::Error::new::h41a97964ab0b8763@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm_bg.wasm:wasm-function[56016]:0x1bd0b0e
console_error_panic_hook::hook_impl::hccf120d22d6ba64c@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm_bg.wasm:wasm-function[14472]:0x1553158
console_error_panic_hook::hook::headc4e1f35397d32@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm_bg.…
[mutiny_wasm.js:2123:21](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
Uncaught (in promise) RuntimeError: unreachable executed
[mutiny_wasm_bg.wasm:29727858:1](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm_bg.wasm)
panicked at 'already borrowed: BorrowMutError', /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasm-bindgen-futures-0.4.33/src/task/singlethread.rs:85:37

Stack:

getImports/imports.wbg.__wbg_new_abda76e883ba8a5f/<@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js:2129:21
logError@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js:232:18
getImports/imports.wbg.__wbg_new_abda76e883ba8a5f@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js:2128:66
console_error_panic_hook::Error::new::h41a97964ab0b8763@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm_bg.wasm:wasm-function[56016]:0x1bd0b0e
console_error_panic_hook::hook_impl::hccf120d22d6ba64c@http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm_bg.wasm:wasm-function[14472]:0x1553158
console_error_panic_hook::hook::headc4e1f35397d32@http://localhost:3420/@fs/dat…
[mutiny_wasm.js:2123:21](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
Uncaught (in promise) RuntimeError: unreachable executed
[mutiny_wasm_bg.wasm:25756811:1](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm_bg.wasm)
INFO mutiny-core/src/logging.rs:27
2023-04-27 20:57:05.535 INFO  [mutiny_core::esplora:316] Finished transaction sync.
```

Afterwards, here's a few logs that might be relevant. It does seem like I did get all the funds on chain, so perhaps not a big worry as far as the funds go.

```
INFO mutiny-core/src/logging.rs:27
2023-04-27 20:58:04.908 INFO  [mutiny_core::esplora:220] Starting transaction sync.
[mutiny_wasm.js:2268:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:58:05.346 DEBUG [lightning::chain::chainmonitor:612] New best block 000001a5755469dd348a12d71f2f4a1eec11f08dcf32633f872dcf4036b8db92 at height 36879 provided via best_block_updated
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:58:05.347 DEBUG [lightning::chain::onchaintx:707] Updating claims view at height 36879 with 0 claim requests
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:58:05.348 DEBUG [lightning::chain::onchaintx:820] Updating claims view at height 36879 with 0 matched transactions in block 36879
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:58:05.349 DEBUG [lightning::chain::onchaintx:707] Updating claims view at height 36879 with 0 claim requests
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:58:05.349 DEBUG [lightning::chain::onchaintx:820] Updating claims view at height 36879 with 0 matched transactions in block 36879
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
INFO mutiny-core/src/logging.rs:27
2023-04-27 20:58:05.431 INFO  [mutiny_core::esplora:316] Finished transaction sync.
```

```
INFO mutiny-core/src/logging.rs:27
2023-04-27 20:59:04.738 INFO  [mutiny_core::esplora:220] Starting transaction sync.
[mutiny_wasm.js:2268:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:59:05.214 DEBUG [lightning::chain::chainmonitor:612] New best block 0000009a7c28c28ac3292d063870ff68bbb051771559303a657e7f5bbcbb9c3d at height 36881 provided via best_block_updated
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:59:05.214 DEBUG [lightning::chain::onchaintx:707] Updating claims view at height 36881 with 0 claim requests
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:59:05.214 DEBUG [lightning::chain::onchaintx:820] Updating claims view at height 36881 with 0 matched transactions in block 36881
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:59:05.216 DEBUG [lightning::chain::onchaintx:707] Updating claims view at height 36881 with 0 claim requests
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 20:59:05.216 DEBUG [lightning::chain::onchaintx:820] Updating claims view at height 36881 with 0 matched transactions in block 36881
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
INFO mutiny-core/src/logging.rs:27
2023-04-27 20:59:05.309 INFO  [mutiny_core::esplora:316] Finished transaction sync.
```

```
INFO mutiny-core/src/logging.rs:27
2023-04-27 21:00:04.922 INFO  [mutiny_core::esplora:220] Starting transaction sync.
[mutiny_wasm.js:2268:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 21:00:05.291 DEBUG [lightning::chain::chainmonitor:612] New best block 00000174cd1bab49d854a7a79fc024e485a18ae59d0c9ebd3b1aad94e578c509 at height 36883 provided via best_block_updated
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 21:00:05.291 DEBUG [lightning::chain::onchaintx:707] Updating claims view at height 36883 with 0 claim requests
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 21:00:05.292 DEBUG [lightning::chain::onchaintx:820] Updating claims view at height 36883 with 0 matched transactions in block 36883
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 21:00:05.293 DEBUG [lightning::chain::onchaintx:707] Updating claims view at height 36883 with 0 claim requests
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
DEBUG mutiny-core/src/logging.rs:26
2023-04-27 21:00:05.293 DEBUG [lightning::chain::onchaintx:820] Updating claims view at height 36883 with 0 matched transactions in block 36883
[mutiny_wasm.js:2271:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
INFO mutiny-core/src/logging.rs:27
2023-04-27 21:00:05.367 INFO  [mutiny_core::esplora:316] Finished transaction sync.
[mutiny_wasm.js:2268:17](http://localhost:3420/@fs/data/Dev/Mutiny/mutiny-node/mutiny-wasm/pkg/mutiny_wasm.js)
```

and it just keeps going like that forever. Keeps updating claims view.

**Comment by benthecarman** [comment]
Yeah the event manager returns a `()` so we have to panic if anything errors :/

Not sure what would be a fix here, maybe getting rid of unwraps and just turning errors into logs

**Comment by benthecarman** [comment]
According to @thebluematt we should persist failures and retry them in the future, at least for spendable outputs.

**Comment by TonyGiorgio** [comment]
I believe this is fixed entirely by the linked PR so I will close it. Will open it again if I see any issues there.
